language: java
dist: trusty


jdk:
  - oraclejdk8

addons:
  chrome: stable
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

before_script:
  - docker-compose up -d
  - sleep 3
  - docker restart angular-api



script:
  - mvn clean test -Dbrowser="headless" -Ddataset="speed-data.json"
  - mvn clean test -Dbrowser="headless" -Ddataset="reliability-data.json"