dist: xenial
language: java

install: true

before_script:
  - docker-compose up -d
  - sleep 3
  - docker restart angular-api



script:
  -mvn clean test -Dbrowser="headless" -Ddataset="speed-data.json"
  -mvn clean test -Dbrowser="headless" -Ddataset="reliability-data.json"